model:
  decoder:
    backbone:
      type: SECOND
      in_channels: 256
      out_channels: [128, 256]
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      norm_cfg:
        type: BN
        eps: 1.0e-3
        momentum: 0.01
      conv_cfg:
        type: Conv2d
        bias: false
    neck:
      type: SECONDFPN
      in_channels: [128, 256]
      out_channels: [256, 256]
      upsample_strides: [1, 2]
      norm_cfg:
        type: BN
        eps: 1.0e-3
        momentum: 0.01
      upsample_cfg:
        type: deconv
        bias: false
      use_conv_for_no_stride: true
  heads:
    object:
      in_channels: 512

#optimizer:
#  type: AdamW
#  lr: 1.0e-4
#  weight_decay: 0.01
#
#optimizer_config:
#  grad_clip:
#    max_norm: 35
#    norm_type: 2
#
#lr_config:
#  policy: cyclic
#
#momentum_config:
#  policy: cyclic

optimizer:
  type: AdamW
  lr: 1.0e-5
  betas: [0.9, 0.999]
  weight_decay: 0.05
  paramwise_cfg:
    custom_keys:
      absolute_pos_embed:
        decay_mult: 0.0
      relative_position_bias_table:
        decay_mult: 0.0
      norm:
        decay_mult: 0.0

optimizer_config:
  grad_clip:
    max_norm: 0.1
    norm_type: 2

lr_config:
  policy: cyclic
  target_ratio: [10, 0.0001]
  cyclic_times: 1
  step_ratio_up: 0.4

momentum_config:
  policy: cyclic
  target_ratio: [0.8947368421052632, 1]
  cyclic_times: 1
  step_ratio_up: 0.4
