voxel_size: [0.075, 0.075, 0.2]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]

model:
  encoders:
    lidar:
      voxelize:
        max_num_points: 10
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [120000, 160000]
      backbone:
        type: SparseLargeKernelEncoder
        in_channels: 5
        sparse_shape: [1440, 1440, 41]
        output_channels: 128
        kernel_sizes: [5, 5, 5, 5]
        conv_types: ['spatialgroupconv', 'common', 'common', 'common']
        kernel_sizes_downsample: [5, 5]
  heads:
    object:
      train_cfg:
        grid_size: [1440, 1440, 41]
      test_cfg:
        grid_size: [1440, 1440, 41]
